CREATE TABLE query_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sql_text TEXT NOT NULL,
    execution_time_ms BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    database_name VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP NOT NULL
);
